spring.application.name=Spring_Security
spring.datasource.url=jdbc:mysql://localhost:3306/security_data
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update


app.jwt-secret="tGagFgM1otrOscxuUN536lVFmrJb9/No8Khx/OBap5I="
app.jwt-expiration-milliseconds=604800000
