package com.tss.banking.service;
import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import com.tss.banking.dto.request.AccountCreationRequestDTO;
import com.tss.banking.dto.response.AccountResponseDTO;
import com.tss.banking.dto.response.AccountSummaryResponseDTO;
import com.tss.banking.entity.Account;
import com.tss.banking.entity.eums.AccountType;
public interface AccountService {
    AccountResponseDTO createAccount(AccountCreationRequestDTO accountCreationRequest);
    AccountResponseDTO getAccountById(Long accountId);
    AccountResponseDTO getAccountByNumber(String accountNumber);
    List<AccountResponseDTO> getAccountsByCustomerId(Long customerId);
    Page<AccountResponseDTO> getAccountsByType(AccountType accountType, Pageable pageable);
    Page<AccountResponseDTO> getAllAccounts(Pageable pageable);
    AccountSummaryResponseDTO getAccountSummary(Long accountId);
    BigDecimal getAccountBalance(Long accountId);
    Account updateAccountBalance(Long accountId, BigDecimal newBalance);
    BigDecimal creditAccount(Long accountId, BigDecimal amount);
    BigDecimal debitAccount(Long accountId, BigDecimal amount);
    void closeAccount(Long accountId);
    AccountResponseDTO reopenAccount(Long accountId);
    boolean existsByAccountNumber(String accountNumber);
    boolean accountBelongsToCustomer(Long accountId, Long customerId);
    Long getAccountOwnerId(Long accountId);
    boolean isAccountActive(Long accountId);
    boolean hasSufficientFunds(Long accountId, BigDecimal amount);
    Account getAccountEntityById(Long accountId);
    Optional<Account> getAccountEntityByNumber(String accountNumber);
    String generateAccountNumber();
    Page<AccountResponseDTO> searchAccounts(String searchTerm, Pageable pageable);
    Page<AccountResponseDTO> getAccountsWithMinBalance(BigDecimal minBalance, Pageable pageable);
    long getAccountCountByType(AccountType accountType);
    BigDecimal getTotalDeposits();
    void deleteAccount(Long accountId);
    AccountResponseDTO createJointAccount(com.tss.banking.dto.request.JointAccountCreationRequestDTO jointAccountRequest);
    AccountResponseDTO addJointAccountHolder(com.tss.banking.dto.request.JointAccountHolderRequestDTO jointHolderRequest);
    AccountResponseDTO removeJointAccountHolder(com.tss.banking.dto.request.JointAccountHolderRequestDTO jointHolderRequest);
    List<com.tss.banking.dto.response.AccountHolderResponseDTO> getJointAccountHolders(Long accountId);
    List<AccountResponseDTO> getAllAccessibleAccountsByCustomerId(Long customerId);
    boolean hasCustomerAccessToAccount(Long accountId, Long customerId);
    Page<AccountResponseDTO> getAllJointAccounts(Pageable pageable);
    AccountResponseDTO convertToJointAccount(Long accountId, List<Long> secondaryCustomerIds);
}
