package com.tss.banking.service;
import java.util.Optional;
import java.util.Set;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import com.tss.banking.dto.request.AdminCreateRequestDTO;
import com.tss.banking.dto.response.AdminResponseDTO;
import com.tss.banking.entity.Admin;
import com.tss.banking.entity.eums.AdminRole;
public interface AdminService {
    AdminResponseDTO createAdmin(AdminCreateRequestDTO adminCreateRequest);
    AdminResponseDTO getAdminById(Long adminId);
    AdminResponseDTO getAdminByEmail(String email);
    Page<AdminResponseDTO> getAllAdmins(Pageable pageable);
    Page<AdminResponseDTO> getAdminsByRole(AdminRole role, Pageable pageable);
    AdminResponseDTO updateAdminRoles(Long adminId, Set<AdminRole> roles);
    AdminResponseDTO addAdminRole(Long adminId, AdminRole role);
    AdminResponseDTO removeAdminRole(Long adminId, AdminRole role);
    boolean existsByEmail(String email);
    boolean hasRole(Long adminId, AdminRole role);
    boolean hasAnyRole(Long adminId, Set<AdminRole> roles);
    Admin getAdminEntityById(Long adminId);
    Optional<Admin> getAdminEntityByEmail(String email);
    Optional<Admin> validateAdminCredentials(String email, String password);
    Page<AdminResponseDTO> searchAdmins(String searchTerm, Pageable pageable);
    void deactivateAdmin(Long adminId);
    AdminResponseDTO activateAdmin(Long adminId);
    void changeAdminPassword(Long adminId, String currentPassword, String newPassword);
    void resetAdminPassword(Long adminId, String newPassword);
    long getTotalAdminCount();
    long getAdminCountByRole(AdminRole role);
    void deleteAdmin(Long adminId);
}
