package com.tss.banking.service;
import java.util.Optional;
import com.tss.banking.dto.request.LoginRequestDTO;
import com.tss.banking.dto.response.AuthResponseDTO;
import com.tss.banking.entity.Admin;
import com.tss.banking.entity.Customer;
public interface AuthService {
    AuthResponseDTO authenticateCustomer(LoginRequestDTO loginRequest);
    AuthResponseDTO authenticateAdmin(LoginRequestDTO loginRequest);
    void logout(String token);
    boolean validateToken(String token);
    Long getUserIdFromToken(String token);
    String getUserEmailFromToken(String token);
    String getUserTypeFromToken(String token);
    boolean isTokenExpired(String token);
    String generateCustomerToken(Customer customer);
    String generateAdminToken(Admin admin);
    boolean isUserLoggedIn(Long userId, String userType);
    Optional<Customer> getCurrentCustomer();
    Optional<Admin> getCurrentAdmin();
    Long getCurrentUserId();
    String getCurrentUserEmail();
    String getCurrentUserType();
    boolean isCurrentUserCustomer();
    boolean isCurrentUserAdmin();
    boolean currentUserHasRole(String requiredRole);
    void invalidateAllUserTokens(Long userId, String userType);
    void cleanupExpiredTokens();
    void logAuthEvent(Long userId, String userType, String action, boolean success, String ipAddress);
}
