package com.tss.banking.service;
import java.util.List;
import java.util.Optional;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import com.tss.banking.dto.request.CustomerApprovalRequestDTO;
import com.tss.banking.dto.request.CustomerRegistrationRequestDTO;
import com.tss.banking.dto.request.CustomerRejectionRequestDTO;
import com.tss.banking.dto.request.CustomerUpdateRequestDTO;
import com.tss.banking.dto.request.PasswordChangeRequestDTO;
import com.tss.banking.dto.response.CustomerResponseDTO;
import com.tss.banking.entity.Customer;
import com.tss.banking.entity.eums.CustomerStatus;
public interface CustomerService {
    CustomerResponseDTO registerCustomer(CustomerRegistrationRequestDTO registrationRequest);
    CustomerResponseDTO updateCustomer(Long customerId, CustomerUpdateRequestDTO updateRequest);
    CustomerResponseDTO getCustomerById(Long customerId);
    CustomerResponseDTO getCustomerByEmail(String email);
    Page<CustomerResponseDTO> getAllCustomers(Pageable pageable);
    Page<CustomerResponseDTO> getCustomersByStatus(CustomerStatus status, Pageable pageable);
    Page<CustomerResponseDTO> searchCustomers(String searchTerm, Pageable pageable);
    void changePassword(Long customerId, PasswordChangeRequestDTO passwordChangeRequest);
    CustomerResponseDTO updateCustomerStatus(Long customerId, CustomerStatus status);
    CustomerResponseDTO activateCustomer(Long customerId);
    CustomerResponseDTO deactivateCustomer(Long customerId);
    CustomerResponseDTO suspendCustomer(Long customerId);
    boolean existsByEmail(String email);
    boolean isCustomerActive(Long customerId);
    Customer getCustomerEntityById(Long customerId);
    Optional<Customer> getCustomerEntityByEmail(String email);
    Optional<Customer> validateCustomerCredentials(String email, String password);
    int getCustomerAccountCount(Long customerId);
    void deleteCustomer(Long customerId);
    List<CustomerResponseDTO> getCustomersPendingApproval();
    Page<CustomerResponseDTO> getCustomersPendingApproval(Pageable pageable);
    CustomerResponseDTO approveCustomer(Long customerId, Long adminId, CustomerApprovalRequestDTO request);
    CustomerResponseDTO rejectCustomer(Long customerId, Long adminId, CustomerRejectionRequestDTO request);
    void fixCustomerPasswordEncoding(String email, String plainPassword);
    CustomerResponseDTO verifyEmail(Long customerId);
    CustomerResponseDTO verifyPhone(Long customerId);
    void fixExistingCustomerVerificationStatus();
}
