package com.tss.banking.service;
import java.math.BigDecimal;
import java.util.List;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import com.tss.banking.dto.request.EMIPaymentRequestDTO;
import com.tss.banking.dto.request.EMIPaymentRequestDTO;
import com.tss.banking.dto.request.LoanApplicationRequestDTO;
import com.tss.banking.dto.request.LoanApprovalRequestDTO;
import com.tss.banking.dto.request.LoanPaymentRequestDTO;
import com.tss.banking.dto.request.LoanRejectionRequestDTO;
import com.tss.banking.dto.response.LoanResponseDTO;
import com.tss.banking.dto.response.TransactionResponseDTO;
import com.tss.banking.entity.Loan;
import com.tss.banking.entity.eums.LoanStatus;
import com.tss.banking.entity.eums.LoanType;
public interface LoanService {
    LoanResponseDTO applyForLoan(LoanApplicationRequestDTO request);
    LoanResponseDTO getLoanById(Long loanId);
    LoanResponseDTO getLoanByNumber(String loanNumber);
    List<LoanResponseDTO> getLoansByCustomerId(Long customerId);
    Page<LoanResponseDTO> getLoansByCustomerId(Long customerId, Pageable pageable);
    List<LoanResponseDTO> getLoansByAccountId(Long accountId);
    List<LoanResponseDTO> getLoansByStatus(LoanStatus status);
    Page<LoanResponseDTO> getLoansByStatus(LoanStatus status, Pageable pageable);
    List<LoanResponseDTO> getLoansByType(LoanType loanType);
    List<LoanResponseDTO> getPendingLoanApplications();
    Page<LoanResponseDTO> getPendingLoanApplications(Pageable pageable);
    LoanResponseDTO approveLoan(Long loanId, Long adminId, LoanApprovalRequestDTO request);
    LoanResponseDTO rejectLoan(Long loanId, Long adminId, LoanRejectionRequestDTO request);
    LoanResponseDTO disburseLoan(Long loanId);
    TransactionResponseDTO makeLoanPayment(LoanPaymentRequestDTO request);
    BigDecimal calculateMonthlyPayment(BigDecimal principal, BigDecimal interestRate, Integer termMonths);
    BigDecimal getTotalOutstandingAmount(Long customerId);
    List<LoanResponseDTO> getLoansWithDuePayments();
    LoanResponseDTO cancelLoanApplication(Long loanId);
    long getLoanCountByCustomer(Long customerId);
    Loan getLoanEntityById(Long loanId);
    Long getLoanApplicantId(Long loanId);
    TransactionResponseDTO processEMIPayment(EMIPaymentRequestDTO request);
    void processAutomaticEMIDeduction(Long loanId);
    void processOverdueLoans();
    List<LoanResponseDTO> getOverdueLoans();
    BigDecimal calculateLateFee(Long loanId);
}
